apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment-blue
  labels:
    app: webapp-blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp-blue
  template:
    metadata:
      labels:
        app: webapp-blue
    spec:
      containers:
      - name: capstone-clouddevops
        image: adeelbarki/capstone-clouddevops
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: webapp-service
spec:
  selector:
    app: webapp-blue
  ports:
  - protocol: TCP
    port: 80
  type: LoadBalancer
---